[tool.black]
line-length = 120
target-version = ['py313']

[tool.isort]
profile = "black"
line_length = 120
known_first_party = ["apps", "core", "config", "infrastructure"]
skip_glob = ["**/migrations/*.py"]

[tool.bandit]
exclude_dirs = ["tests", "*/migrations/*"]
tests = ["B101"]

[tool.mypy]
python_version = "3.13"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true
disallow_untyped_defs = true
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "config.settings"

# --- Strict Behavior (Optional, but recommended) ---
# disallow_any_unimported = true
# disallow_any_explicit = true
# disallow_any_generics = true
# disallow_subclassing_any = true
# disallow_untyped_calls = true
# disallow_incomplete_defs = true
# check_untyped_defs = true
# no_implicit_optional = true
# warn_redundant_casts = true
# warn_unused_ignores = true
