# Generated by Django 5.2.3 on 2025-06-30 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("paid", "Paid"),
                            ("uncollectible", "Uncollectible"),
                            ("void", "Voided"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="issued at"),
                ),
                ("due_date", models.DateField(verbose_name="due date")),
                ("period_start", models.DateField(verbose_name="period start")),
                ("period_end", models.DateField(verbose_name="period end")),
                (
                    "currency",
                    models.CharField(default="USD", max_length=3, verbose_name="currency"),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="subtotal"),
                ),
                (
                    "tax_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="total taxes",
                    ),
                ),
                (
                    "discount_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="total discounts",
                    ),
                ),
                (
                    "amount_due",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="amount due"),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="amount paid",
                    ),
                ),
                (
                    "invoice_pdf_url",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="invoice PDF URL",
                    ),
                ),
                (
                    "gateway_invoice_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="gateway invoice ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "invoice",
                "verbose_name_plural": "invoices",
                "db_table": "invoices",
            },
        ),
        migrations.CreateModel(
            name="InvoiceLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(verbose_name="description")),
                ("quantity", models.IntegerField(default=1, verbose_name="quantity")),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="unit price"),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="amount"),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("subscription", "Subscription"),
                            ("usage", "Usage"),
                            ("one_time", "One-time charge"),
                            ("discount", "Discount"),
                            ("tax", "Tax"),
                            ("credit", "Credit"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="type",
                    ),
                ),
                (
                    "period_starts_at",
                    models.DateField(blank=True, null=True, verbose_name="period start"),
                ),
                (
                    "period_ends_at",
                    models.DateField(blank=True, null=True, verbose_name="period end"),
                ),
                (
                    "unit_price_tier",
                    models.JSONField(
                        blank=True,
                        help_text="The pricing tier that was applied.",
                        null=True,
                        verbose_name="unit price tier",
                    ),
                ),
            ],
            options={
                "verbose_name": "invoice line",
                "verbose_name_plural": "invoice lines",
                "db_table": "invoice_line_items",
            },
        ),
        migrations.CreateModel(
            name="InvoiceLineItemUsageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Line Item Usage Record",
                "verbose_name_plural": "Invoice Line Item Usage Records",
                "db_table": "invoice_line_item_usage_records",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="amount"),
                ),
                (
                    "currency",
                    models.CharField(default="USD", max_length=3, verbose_name="currency"),
                ),
                (
                    "gateway_transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="gateway transaction ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="paid at"),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        help_text="Used to store gateway responses, etc.",
                        null=True,
                        verbose_name="details",
                    ),
                ),
            ],
            options={
                "verbose_name": "payment",
                "verbose_name_plural": "payments",
                "db_table": "payments",
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("credit_card", "Credit Card"),
                            ("paypal", "PayPal"),
                            ("bank_account", "Bank Account"),
                        ],
                        max_length=50,
                        verbose_name="method type",
                    ),
                ),
                (
                    "gateway_payment_method_id",
                    models.CharField(max_length=255, unique=True, verbose_name="gateway method ID"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="is default"),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        help_text="Last 4 digits, expiration date, etc. NEVER sensitive data.",
                        null=True,
                        verbose_name="details",
                    ),
                ),
            ],
            options={
                "verbose_name": "payment method",
                "verbose_name_plural": "payment methods",
                "db_table": "payment_methods",
            },
        ),
        migrations.CreateModel(
            name="UsageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Supports fractional values (e.g., GB, hours).",
                        max_digits=18,
                        verbose_name="quantity",
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="recorded at"),
                ),
                ("event_time", models.DateTimeField(verbose_name="event time")),
                (
                    "source_ip",
                    models.GenericIPAddressField(blank=True, null=True, verbose_name="source IP"),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        help_text="External resource ID (e.g., transaction ID).",
                        max_length=255,
                        null=True,
                        verbose_name="reference ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "usage record",
                "verbose_name_plural": "usage records",
                "db_table": "usage_records",
            },
        ),
        migrations.CreateModel(
            name="CreditTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="amount"),
                ),
                (
                    "balance_after",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="balance after"),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase"),
                            ("usage", "Usage"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=20,
                        verbose_name="transaction type",
                    ),
                ),
                (
                    "reference_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Link to payments/invoices.",
                        null=True,
                        verbose_name="reference ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenancies.tenant",
                        verbose_name="tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "credit transaction",
                "verbose_name_plural": "credit transactions",
                "db_table": "credit_transactions",
            },
        ),
    ]
