# Generated by Django 5.2.3 on 2025-06-30 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0001_initial"),
        ("business", "0001_initial"),
        ("tenancies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="business.subscription",
                verbose_name="subscription",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tenancies.tenant",
                verbose_name="tenant",
            ),
        ),
        migrations.AddField(
            model_name="invoicelineitem",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="line_items",
                to="billing.invoice",
                verbose_name="invoice",
            ),
        ),
        migrations.AddField(
            model_name="invoicelineitem",
            name="usage_feature",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="business.feature",
                verbose_name="usage feature",
            ),
        ),
        migrations.AddField(
            model_name="invoicelineitemusagerecord",
            name="invoice_line_item",
            field=models.ForeignKey(
                db_column="invoice_line_item_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usage_records",
                to="billing.invoicelineitem",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="billing.invoice",
                verbose_name="invoice",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tenancies.tenant",
                verbose_name="tenant",
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tenancies.tenant",
                verbose_name="tenant",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="billing.paymentmethod",
                verbose_name="payment method",
            ),
        ),
        migrations.AddField(
            model_name="usagerecord",
            name="feature",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="business.feature",
                verbose_name="feature",
            ),
        ),
        migrations.AddField(
            model_name="usagerecord",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tenancies.tenant",
                verbose_name="tenant",
            ),
        ),
    ]
