# Generated by Django 5.2.3 on 2025-06-30 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="usagerecord",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="invoicelineitemusagerecord",
            name="usage_record",
            field=models.ForeignKey(
                db_column="usage_record_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice_line_items",
                to="billing.usagerecord",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["tenant"], name="idx_invoices_tenant_id"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["status"], name="idx_invoices_status"),
        ),
        migrations.AlterUniqueTogether(
            name="invoice",
            unique_together={("subscription", "period_end")},
        ),
        migrations.AddIndex(
            model_name="invoicelineitem",
            index=models.Index(fields=["invoice"], name="idx_invoice_line_id"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["tenant"], name="idx_payments_tenant_id"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["invoice"], name="idx_payments_invoice_id"),
        ),
        migrations.AddIndex(
            model_name="usagerecord",
            index=models.Index(
                fields=["tenant", "feature"], name="idx_usg_rec_tenant_feat"
            ),
        ),
        migrations.AddIndex(
            model_name="usagerecord",
            index=models.Index(
                fields=["event_time"], name="idx_usage_records_event_time"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="invoicelineitemusagerecord",
            unique_together={("invoice_line_item", "usage_record")},
        ),
    ]
