# Generated by Django 5.2.3 on 2025-06-29 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_deleted_at_alter_user_is_active"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="user",
            name="idx_users_tenant_id",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="idx_users_tenant_id_is_active",
        ),
        migrations.AlterUniqueTogether(
            name="user",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="user",
            name="tenant",
        ),
    ]
