# Generated by Django 5.2.3 on 2025-06-23 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("tenancies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="departmentuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="departmentuser",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="tenancies.role",
                verbose_name="role",
            ),
        ),
        migrations.AddField(
            model_name="rolepermission",
            name="permission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="auth.permission"
            ),
        ),
        migrations.AddField(
            model_name="rolepermission",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenancies.role"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(
                through="tenancies.RolePermission",
                to="auth.permission",
                verbose_name="permissions",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="parent_tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="For hierarchical structures (resellers, etc.)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tenancies.tenant",
                verbose_name="parent tenant",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="tenant",
            field=models.ForeignKey(
                help_text="Null for global system roles.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="tenancies.tenant",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tenancies.tenant",
                verbose_name="tenant",
            ),
        ),
        migrations.AddField(
            model_name="tenantconfiguration",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenancies.tenant"
            ),
        ),
        migrations.AddField(
            model_name="usertenantrole",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="tenancies.role",
                verbose_name="role",
            ),
        ),
        migrations.AddField(
            model_name="usertenantrole",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tenancies.tenant",
                verbose_name="tenant",
            ),
        ),
        migrations.AddField(
            model_name="usertenantrole",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddIndex(
            model_name="departmentuser",
            index=models.Index(fields=["user"], name="idx_dept_users_user_id"),
        ),
        migrations.AddIndex(
            model_name="departmentuser",
            index=models.Index(fields=["department"], name="idx_dept_users_dept_id"),
        ),
        migrations.AlterUniqueTogether(
            name="departmentuser",
            unique_together={("user", "department")},
        ),
        migrations.AlterUniqueTogether(
            name="rolepermission",
            unique_together={("role", "permission")},
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["tenant"], name="idx_roles_tenant_id"),
        ),
        migrations.AlterUniqueTogether(
            name="role",
            unique_together={("tenant", "name")},
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["tenant"], name="idx_departments_tenant_id"),
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("tenant", "name")},
        ),
        migrations.AddIndex(
            model_name="usertenantrole",
            index=models.Index(fields=["user"], name="idx_u_user_tenant_roles_id"),
        ),
        migrations.AddIndex(
            model_name="usertenantrole",
            index=models.Index(fields=["tenant"], name="idx_t_user_tenant_roles_id"),
        ),
        migrations.AlterUniqueTogether(
            name="usertenantrole",
            unique_together={("user", "tenant", "role")},
        ),
    ]
