# Generated by Django 5.2.3 on 2025-06-23 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userdepartmentrole",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="usertenantrole",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="tenancies.role",
                verbose_name="role",
            ),
        ),
        migrations.AddField(
            model_name="usertenantrole",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tenancies.tenant",
                verbose_name="tenant",
            ),
        ),
        migrations.AddField(
            model_name="usertenantrole",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rolepermission",
            unique_together={("role", "permission")},
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["tenant"], name="idx_roles_tenant_id"),
        ),
        migrations.AlterUniqueTogether(
            name="role",
            unique_together={("tenant", "name")},
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["tenant"], name="idx_departments_tenant_id"),
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("tenant", "name")},
        ),
        migrations.AddIndex(
            model_name="userdepartmentrole",
            index=models.Index(fields=["user"], name="idx_dept_users_user_id"),
        ),
        migrations.AddIndex(
            model_name="userdepartmentrole",
            index=models.Index(fields=["department"], name="idx_dept_users_dept_id"),
        ),
        migrations.AlterUniqueTogether(
            name="userdepartmentrole",
            unique_together={("user", "department", "role")},
        ),
        migrations.AddIndex(
            model_name="usertenantrole",
            index=models.Index(fields=["user"], name="idx_u_user_tenant_roles_id"),
        ),
        migrations.AddIndex(
            model_name="usertenantrole",
            index=models.Index(fields=["tenant"], name="idx_t_user_tenant_roles_id"),
        ),
        migrations.AlterUniqueTogether(
            name="usertenantrole",
            unique_together={("user", "tenant", "role")},
        ),
    ]
