# Generated by Django 5.2.3 on 2025-06-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancies", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="deleted_at",
            field=models.DateTimeField(null=True, verbose_name="deleted at"),
        ),
    ]
