# Generated by Django 5.2.3 on 2025-06-29 03:30

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancies", "0003_department_is_active_tenant_is_active_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantAuditPolicy",
            fields=[
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="tenancies.tenant",
                        verbose_name="tenant",
                    ),
                ),
                (
                    "log_retention_days",
                    models.IntegerField(default=365, verbose_name="log retention days"),
                ),
                (
                    "require_log_signatures",
                    models.BooleanField(
                        default=False, verbose_name="require log signatures"
                    ),
                ),
                (
                    "sensitive_tables",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        help_text="Tables that are logged in sensitive_access_logs.",
                        size=None,
                        verbose_name="sensitive tables",
                    ),
                ),
            ],
            options={
                "verbose_name": "tenant audit policy",
                "verbose_name_plural": "tenant audit policies",
                "db_table": "tenant_audit_policies",
            },
        ),
        migrations.AddField(
            model_name="tenant",
            name="available_credits",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="available credits",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="billing_strategy",
            field=models.CharField(
                default="subscription", max_length=50, verbose_name="billing strategy"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="data_retention_policy",
            field=models.JSONField(
                blank=True, null=True, verbose_name="data retention policy"
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="deleted_at",
            field=models.DateTimeField(null=True, verbose_name="deleted at"),
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "invitee_email",
                    models.EmailField(max_length=254, verbose_name="invitee email"),
                ),
                (
                    "token",
                    models.CharField(max_length=64, unique=True, verbose_name="token"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        default="pending",
                        max_length=50,
                        verbose_name="status",
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="expires at")),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenancies.department",
                        verbose_name="organization",
                    ),
                ),
                (
                    "invited_by_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="invited by",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenancies.role",
                        verbose_name="assigned role",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenancies.tenant",
                        verbose_name="tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "invitation",
                "verbose_name_plural": "invitations",
                "db_table": "invitations",
                "indexes": [
                    models.Index(fields=["tenant"], name="idx_invitations_tenant_id"),
                    models.Index(fields=["department"], name="idx_invit_dep_id"),
                ],
            },
        ),
    ]
