# Generated by Django 5.2.3 on 2025-06-30 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("audit", "0001_initial"),
        ("business", "0002_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("tenancies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="actor_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="actor",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="target_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
                verbose_name="object type",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tenancies.tenant",
                verbose_name="tenant",
            ),
        ),
        migrations.AddField(
            model_name="auditmetric",
            name="feature",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="business.feature",
                verbose_name="feature",
            ),
        ),
        migrations.AddField(
            model_name="auditmetric",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tenancies.tenant",
                verbose_name="tenant",
            ),
        ),
        migrations.AddField(
            model_name="metadataaudit",
            name="changed_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="changed by",
            ),
        ),
        migrations.AddField(
            model_name="metadataaudit",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tenancies.tenant",
                verbose_name="tenant",
            ),
        ),
        migrations.AddField(
            model_name="sensitiveaccesslog",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tenancies.tenant",
                verbose_name="tenant",
            ),
        ),
        migrations.AddField(
            model_name="sensitiveaccesslog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="auditlogsignature",
            name="signer_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="signer",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["tenant", "-created_at"], name="idx_logs_tenant_created_at"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["target_content_type", "target_object_id"],
                name="idx_audit_logs_target",
            ),
        ),
        migrations.AddIndex(
            model_name="auditmetric",
            index=models.Index(fields=["tenant"], name="idx_audit_metrics_tenant_id"),
        ),
        migrations.AddIndex(
            model_name="auditmetric",
            index=models.Index(fields=["feature"], name="idx_audit_metrics_feature_id"),
        ),
        migrations.AlterUniqueTogether(
            name="auditmetric",
            unique_together={("tenant", "feature", "measured_at")},
        ),
    ]
