# Generated by Django 5.2.3 on 2025-06-30 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("authentication", "0001_initial"),
        ("tenancies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="invited_by_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="invited by",
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tenancies.tenant",
                verbose_name="tenant",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="group",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="auth.group"
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.role",
                verbose_name="assigned role",
            ),
        ),
        migrations.AddField(
            model_name="rolepermission",
            name="permission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="auth.permission"
            ),
        ),
        migrations.AddField(
            model_name="rolepermission",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="authentication.role"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(
                through="authentication.RolePermission",
                to="auth.permission",
                verbose_name="permissions",
            ),
        ),
        migrations.AddField(
            model_name="userdepartmentrole",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tenancies.department",
                verbose_name="department",
            ),
        ),
        migrations.AddField(
            model_name="userdepartmentrole",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="authentication.role",
                verbose_name="role",
            ),
        ),
        migrations.AddField(
            model_name="userdepartmentrole",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="usertenantrole",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="authentication.role",
                verbose_name="role",
            ),
        ),
        migrations.AddField(
            model_name="usertenantrole",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tenancies.tenant",
                verbose_name="tenant",
            ),
        ),
        migrations.AddField(
            model_name="usertenantrole",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(fields=["tenant"], name="idx_invitations_tenant_id"),
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(fields=["department"], name="idx_invit_dep_id"),
        ),
        migrations.AlterUniqueTogether(
            name="rolepermission",
            unique_together={("role", "permission")},
        ),
        migrations.AddIndex(
            model_name="userdepartmentrole",
            index=models.Index(fields=["user"], name="idx_dept_users_user_id"),
        ),
        migrations.AddIndex(
            model_name="userdepartmentrole",
            index=models.Index(fields=["department"], name="idx_dept_users_dept_id"),
        ),
        migrations.AlterUniqueTogether(
            name="userdepartmentrole",
            unique_together={("user", "department", "role")},
        ),
        migrations.AddIndex(
            model_name="usertenantrole",
            index=models.Index(fields=["user"], name="idx_u_user_tenant_roles_id"),
        ),
        migrations.AddIndex(
            model_name="usertenantrole",
            index=models.Index(fields=["tenant"], name="idx_t_user_tenant_roles_id"),
        ),
        migrations.AlterUniqueTogether(
            name="usertenantrole",
            unique_together={("user", "tenant", "role")},
        ),
    ]
